so ~/.vim/plugged/config/normal_mode_shortcuts.vim
so ~/.vim/plugged/config/color.vim
so ~/.vim/plugged/config/cammand_mode_shortcuts.vim
so ~/.vim/plugged/config/insert_mode_shortcuts.vim
so ~/.vim/plugged/config/visual_mode_shortcuts.vim
so ~/.vim/plugged/config/vimonlyrc.vim
so ~/.vim/plugged/config/custom.vim
so ~/.vim/plugged/config/other.vim
so ~/.vim/plugged/config/plugins.vim
